apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  labels:
    name: secret-config
type: Opaque
stringData:
  FASTFOOD_JDBC_URL: "jdbc:postgresql://postgresdb-service:5432/fastfood"
  FASTFOOD_DB_HOST: "postgresdb-service"
  FASTFOOD_DB_NAME: "fastfood"
  FASTFOOD_DB_PORT: "5432"
  FASTFOOD_DB_USER: "postgres"
  FASTFOOD_DB_PASSWORD: "1234"
