apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  FASTFOOD_DB_HOST: "postgresdb-service"
  FASTFOOD_DB_PORT: ":5432"
  FASTFOOD_DB_NAME: "fastfood"
  FASTFOOD_DB_USER: "postgres"
  FASTFOOD_DB_PASSWORD: "1234"
