name: Deploy FastFood API

on:
  push:
    branches:
      - master  # Executa o pipeline apenas na branch master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Agora está configurado para Java 21
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn clean install -DskipTests  # Compila o projeto e cria o JAR

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar imagem para Docker Hub
        run: |
          VERSION=$(date +%s)  # Usa timestamp como versão da imagem
          docker build -t rm359211/fastfood-app:$VERSION .  # Build da imagem Docker
          docker push rm359211/fastfood-app:$VERSION       # Push para o Docker Hub
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV  # Salva a versão da imagem no ambiente do GitHub

      - name: Conectar à EC2 e rodar os comandos do Kubernetes
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Iniciar o Minikube se necessário
            echo "Iniciando Minikube..."
            minikube start

            # Configurar o kubectl para usar o contexto Minikube
            echo "Configuring kubectl to use minikube context..."
            kubectl config use-context minikube

            # Atualizando a imagem do Kubernetes
            echo "Atualizando imagem no Kubernetes..."
            kubectl set image deployment/fastfoodapi-deployment fastfoodapi-pod=rm359211/fastfood-app:$IMAGE_VERSION
            kubectl rollout status deployment/fastfoodapi-deployment

            # Aplicando configurações do Kubernetes
            echo "Aplicando configurações do Kubernetes..."
            kubectl apply -f k8s-infra/env/secret.yaml
            kubectl apply -f k8s-infra/env/configmap.yaml
            kubectl apply -f k8s-infra/db/postgresdb-statefulset.yaml
            kubectl apply -f k8s-infra/db/postgresdb-service.yaml
            kubectl apply -f k8s-infra/fastfoodapi/fastfoodapi-deployment.yaml
            kubectl apply -f k8s-infra/fastfoodapi/fastfoodapi-service.yaml
            kubectl apply -f k8s-infra/hpa/fastfoodapi-hpa.yaml
